export {default as WebHostService} from "./WebHostService.js";
export {default as StaticResource} from "./StaticResource.js";
export {default as JsonRpcResource} from "./JsonRpcResource.js";
export {default as WsRpcResource} from "./WsRpcResource.js";
export {default as SPAResource} from "./SPAResource.js";
export {default as createJsonRPCClient} from "./createJsonRPCClient.js";
export {default as createWsRPCClient} from "./createWsRPCClient.js";
export type {WebResource} from "./types.js";
export {AuthConfigSchema, WebHostConfigSchema} from "./schema.js";
export type {ParsedAuthConfig, ParsedWebHostConfig} from "./schema.js";
export {spaResourceConfigSchema} from "./SPAResource.js";
export {staticResourceConfigSchema} from "./StaticResource.js";
