export {default as WebHostService} from "./WebHostService.ts";
export {default as StaticResource} from "./StaticResource.ts";
export {default as JsonRpcResource} from "./JsonRpcResource.ts";
export {default as WsRpcResource} from "./WsRpcResource.ts";
export {default as SPAResource} from "./SPAResource.ts";
export {default as createJsonRPCClient} from "./createJsonRPCClient.ts";
export {default as createWsRPCClient} from "./createWsRPCClient.ts";
export type {WebResource} from "./types.ts";
export {AuthConfigSchema, WebHostConfigSchema} from "./schema.ts";
export type {ParsedAuthConfig, ParsedWebHostConfig} from "./schema.ts";
export {spaResourceConfigSchema} from "./SPAResource.ts";
export {staticResourceConfigSchema} from "./StaticResource.ts";
